# Generated by Django 5.0.1 on 2024-04-21 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divisions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('division', models.CharField(choices=[('Руководство', 'Руководство'), ('Отдел разработки',
                'Отдел разработки'), ('Отдел бухгалтерии', 'Отдел бухгалтерии'), ('Отдел экономики',
                'Отдел экономики')], default='ГД', max_length=75, verbose_name='Подразделение')),
                ('division_number', models.CharField(blank=True, max_length=12, null=True,
                                                     verbose_name='Подразделение - телефон')),
                ('division_description', models.CharField(blank=True, max_length=100, null=True,
                                                          verbose_name='Описание подразделения')),
                ('division_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True,
                                                   verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_pattern', models.CharField(choices=[('Полный', 'Полный'), ('Охрана', 'Охрана'), ('Уборщики', 'Уборщики'), ('Посетители', 'Посетители'), ('Бухгалтерия', 'Бухгалтерия'), ('Менеджер', 'Менеджер')], default='П', max_length=50, verbose_name='Шаблон доступа')),
                ('access_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание доступа')),
                ('pattern_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Шаблоны доступа',
                'verbose_name_plural': 'Шаблон доступа',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post', models.CharField(choices=[('Генеральный директор', 'Генеральный директор'), ('Главный инженер', 'Главный инженер'), ('Главный бухгалтер', 'Главный бухгалтер'), ('Экономист', 'Экономист'), ('Бухгалтер', 'Бухгалтер'), ('Менеджер по продажам', 'Менеджер по продажам')], default='Р', max_length=75, verbose_name='Должность')),
                ('post_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание Должности')),
                ('post_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_task', models.CharField(choices=[('Резервное копирование базы данных', 'Резервное копирование базы данных'), ('Задача', 'Задача')], default='РК', max_length=75, verbose_name='Название задачи')),
                ('time_of_cmlt', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Втроник', 'Втроник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='ПН', max_length=75, verbose_name='Когда выполнять')),
                ('status_task', models.CharField(choices=[('Выполнено', 'Выполнено'), ('Запланировано', 'Запланировано')], default='Запланировано', max_length=75, verbose_name='Статус выполнения')),
                ('date_task', models.DateTimeField(blank=True, null=True, verbose_name='Дата')),
                ('task_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Задание системы',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=150, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Номер телефона')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('employee_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('date_join', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Дата последнего входа')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='personal_photo', verbose_name='Фотография')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.divisions', verbose_name='Подразделение')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.patterns', verbose_name='Шаблон доступа')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.posts', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Наименование документа')),
                ('doc_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('division', models.ForeignKey(blank=True, default='Отдел логистики', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.divisions', verbose_name='Подразделение')),
                ('operator_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
            },
        ),
        migrations.CreateModel(
            name='ExplanatoryNotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('Служебная командировка', 'Служебная командировка'), ('Отпуск по беременности и родам', 'Отпуск по беременности и родам')], default='СК', max_length=75, verbose_name='Название типа документа')),
                ('add_work_hours', models.CharField(choices=[('Добавлять', 'Добавлять'), ('Не добавлять', 'Не добавлять')], default='НД', max_length=75, verbose_name='Добавление к рабочему времени')),
                ('fine', models.CharField(choices=[('В календарных днях включая праздничные', 'В календарных днях включая праздничные'), ('В рабочих днях', 'В рабочих днях')], default='РД', max_length=75, verbose_name='Способ исчисления')),
                ('explanatory_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Объяснительная',
                'verbose_name_plural': 'Объяснительные',
            },
        ),
        migrations.CreateModel(
            name='Operators',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=150, verbose_name='Логин')),
                ('post_operator', models.CharField(choices=[('Главный администратор', 'Главный администратор'), ('Администратор', 'Администратор')], default='МА', max_length=75, verbose_name='Роль')),
                ('operator_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание оператора')),
                ('operator_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'Оператор',
                'verbose_name_plural': 'Операторы',
            },
        ),
        migrations.CreateModel(
            name='Visiting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor', models.CharField(max_length=150, verbose_name='Посетитель')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Временный пропуск с:')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Временный пропуск по:')),
                ('visitor_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('division', models.ForeignKey(blank=True, default='Отдел логистики', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.divisions', verbose_name='Подразделение')),
                ('maintainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сопровождающий')),
            ],
            options={
                'verbose_name': 'Посетителя',
                'verbose_name_plural': 'Посещения',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Тип графика с:')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Тип графика до:')),
                ('time_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название графика')),
                ('time_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Описание рабочего графика')),
                ('time_status', models.CharField(choices=[('Активен', 'Активен'), ('Устарел', 'Устарел'), ('Отключен', 'Отключен')], default='А', max_length=25, verbose_name='Статус графика')),
                ('time_slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL')),
                ('division', models.ForeignKey(blank=True, default='Отдел логистики', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.divisions', verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'График работы',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.workschedule', verbose_name='Тип графика'),
        ),
    ]
