# Generated by Django 5.0.1 on 2024-05-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/', verbose_name='Файл документа'),
        ),
    ]
